name: Workflow - base

on:
  push:
    branches:
    - main

jobs:
  test-linux-x86:
    if: true
    runs-on: ubuntu-22.04
    steps:
    - id: checkout-code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python Components
      run: |
        pip install --upgrade setuptools wheel
        pip install nuitka

    - name: Compile with Nuitka
      run: python3 xia_nuitka/compiler.py tests xia_tests linux

    - name: Build Wheel Package
      run: |
        cd tests
        python3 setup.py bdist_wheel --python-tag cp310 --plat-name manylinux1_x86_64 clean --all

    - name: Install Built Package
      run:
        pip install tests/dist/xia_tests-0.1.0-cp310-none-manylinux1_x86_64.whl

    - name: Test Built Package
      run:
        python3 -c "from xia_tests.communicate import Communicate"

  test-macos-x86:
    if: false
    runs-on: macos-13
    steps:
    - id: checkout-code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install CCache
      run: brew install ccache

    - name: Install Python Components
      run: |
        pip install --upgrade setuptools wheel
        pip install nuitka

    - name: Compile with Nuitka
      run: python3 xia_nuitka/compiler.py tests xia_tests macos

    - name: Build Wheel Package
      run: |
        cd tests
        python3 setup.py bdist_wheel --python-tag cp310 --plat-name macosx_11_0_x86_64 clean --all

    - name: Install Built Package
      run:
        pip install tests/dist/xia_tests-0.1.0-cp310-none-macosx_11_0_x86_64.whl

    - name: Test Built Package
      run:
        python3 -c "from xia_tests.communicate import Communicate"

  test-win:
    if: true
    runs-on: windows-2022
    steps:
    - id: checkout-code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python Components
      run: |
        pip install --upgrade setuptools wheel
        pip install nuitka

    - name: Compile with Nuitka
      run: python3 xia_nuitka/compiler.py tests xia_tests win

    - name: Build Wheel Package
      run: |
        cd tests
        python3 -m build --python-tag cp310 --plat-name win_amd64 clean --all

    - name: Install Built Package
      run:
        pip install tests/dist/xia_tests-0.1.0-cp310-none-win_amd64.whl

    - name: Test Built Package
      run:
        python3 -c "from xia_tests.communicate import Communicate"
