name: Workflow - base

on:
  push:
    branches:
    - main

jobs:
  test:
    name: Build & Test (Python ${{ matrix.python }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
        python: ["3.10"]
    steps:
    - id: checkout-code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install Python Components
      run: |
        pip install --upgrade setuptools wheel
        pip install nuitka

    - name: Compile with Nuitka
      run: python3 xia_nuitka/compiler.py compile tests xia_tests

    - name: Build Wheel Package
      run: |
        cd tests
        python3 ../xia_nuitka/compiler.py build

    - name: Install Built Package
      run:
        pip install tests/dist/xia_tests-*.whl

    - name: Test Built Package
      run:
        python3 tests/run.py
