name: Workflow - base

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - id: checkout-code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Nuitka
      run: pip install nuitka

    - name: Compile with Nuitka
      run: python3 xia_nuitka/linux.py tests xia_tests linux